concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

name: Publish Table

on:
    push:
        tags:
            - "table.[0-9]+.[0-9]+.[0-9]+"
    workflow_dispatch:

jobs:
    publish:
        runs-on: macos-latest
        name: Publish Table
        timeout-minutes: 60
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                name: Setup Java
                with:
                    distribution: 'oracle'
                    java-version: '17'

            -   name: Setup gradle
                uses: gradle/actions/setup-gradle@v4
                with:
                    cache-read-only: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
                    gradle-home-cache-includes: |
                        caches
                        notifications
                    gradle-home-cache-cleanup: true
                env:
                    GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

            -   uses: Infisical/secrets-action@v1.0.9
                with:
                    client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }} # Update this to your own Github references
                    client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }} # Update this to your own Github references
                    env-slug: "prod"
                    project-slug: "compose-table-z-aw-w"
                    secret-path: "/publish"
                    domain: https://eu.infisical.com

            -   name: Prepare Release Version
                id: prepareVersion
                run: |
                    RESULT=$(echo ${{ github.ref_name }} | sed 's/table.//g')
                    echo "versionName=$RESULT" >> $GITHUB_OUTPUT    

            -   name: Environment
                run: |
                    touch .env
                    echo "VERSION_NAME=${{ steps.prepareVersion.outputs.versionName }}" >> .env
                    
            -   name: Publish to MavenCentral
                run: ./gradlew :compose-data-table:publishToMavenCentral --stacktrace --quiet